export const roastingLines = [
  'Pro tip: Windows exist for a reason!',
  "Thanos snapped... and the weather changed.",
  "Weather app developers hate this one simple trick...",
  "Save data and battery - just look outside!",
  "Congratulations! You've just been bamboozled!",
  "Modern problems require medieval solutions!",
  "Breaking news: Outside still exists!",
  "This is why your phone battery lasts longer than mine.",
  "Weather forecasting technology since 100,000 BC.",
  "I'm not lazy, I'm resource efficient!",
  "5 out of 5 grandparents recommend this method.",
  "Weather forecast accuracy: 100% guaranteed!",
  "Your weather radar is called a window, try it sometime.",
  "Why use satellites when you have eyeballs?",
  "App usage time: 30 seconds. Time wasted: 30 seconds.",
  "Weather forecasting, reinvented for the lazy generation!",
  "Our advanced algorithm = looking out the window.",
  "Spoiler alert: The weather is right there!",
  "Downloading weather data the old-fashioned way - using your eyes.",
  "The only weather app with zero server costs!",
  "Congratulations on taking the longest route to check the weather!",
  "Forecasting with 100% less technology, 100% more common sense.",
  "Opening a window: Nature's weather API.",
  "This app was sponsored by the Window Manufacturing Association.",
  "Most revolutionary weather technology since the thermometer!",
  "Even cavemen knew to just look outside.",
  "We've secretly replaced their weather app with actual windows. Let's see if they notice!",
  "Warning: Prolonged usage may result in self-awareness.",
  "The most environmentally friendly weather app - uses zero electricity!",
  "When technology fails, windows prevail.",
  "Meteorologists HATE this one simple trick!",
  "This app is 80% sarcasm, 20% weather.",
  "Powered by a team of highly trained hamsters.",
  "Accuracy not guaranteed. Sanity not guaranteed.",
  "We predict the weather with the accuracy of a broken clock... twice a day!",
  "I am Iron Man... I mean, Weather Man.",
  "Thanos snapped... and the weather changed.",
  "This app is my weapon... my *weather* weapon.",
];

export const loadingMessages = [
  "Analyzing cloud patterns...",
  "Connecting to weather satellites...",
  "Fetching meteorological data...",
  "Calculating precipitation probability...",
  "Scanning atmospheric conditions...",
  "Interrogating weather fairies...",
  "Bribing the weather gods...",
  "Converting weather data to emojis...",
  "Performing advanced weather magic...",
  "Consulting with meteorologists...",
  "Downloading weather from the Cloud...",
  "Calibrating the flux capacitor...",
  "Summoning weather spirits...",
  "Consulting the magic 8-ball...",
  "Asking Jarvis for the forecast...",
  "Harnessing the power of the Tesseract...",
  "Consulting the Ancient One...",
  "Checking with Nick Fury...",
];

export const weatherFacts = [
  "🌧️ A single thunderstorm can use more energy than an atomic bomb!",
  "❄️ No two snowflakes are exactly alike, but they all have six sides.",
  "🌪️ The fastest recorded wind speed on Earth was 253 mph during a tropical cyclone in Australia.",
  "🔥 The highest temperature ever recorded on Earth was 134°F (56.7°C) in Death Valley, California.",
  "🧊 The coldest temperature ever recorded was -128.6°F (-89.2°C) in Antarctica.",
  "⚡ Lightning strikes Earth about 8.6 million times per day!",
  "☂️ The wettest place on Earth is Mawsynram, India, with an average of 467 inches of rain per year.",
  "🌈 Rainbows are actually full circles, but we usually only see half from the ground.",
  "🌞 It takes sunlight about 8 minutes to reach Earth.",
  "☔ The fastest raindrop can fall at speeds of 18 mph!",
  "🌩️ Thunder is the sound of lightning rapidly heating the air around it.",
  "☁️ A typical cloud weighs about 1.1 million pounds!",
  "🌡️ The air temperature decreases about 5.4°F for every 1,000 feet you go up in elevation.",
  "❄️ About 1 million billion snowflakes fall each second across the Earth during a snowstorm.",
  "🧠 Humans are surprisingly good weather predictors - about 70% accurate just by looking at the sky!",
  "🍌 Bananas are berries, but strawberries aren't. (Not weather-related, but interesting!)",
  "🦆 Ducks can sleep with one eye open. (Also not weather, but still cool!)",
  "The weather is often stranger than anything we could imagine. (Just like the multiverse!)",
  "Some people can literally 'smell' rain coming. (Like a superpower!)",
];

export const specialLocations: Record<string, string> = {
  'north pole': "It's cold. Really cold. Genius!",
  hawaii: "It's a tropical paradise, what did you expect?",
  sahara: 'Hot. Sand. More sand. What else do you need to know?',
  atlantis: '100% chance of being underwater. Forever.',
  'your room': 'Maybe clean it first, then check the weather?',
  mars: 'No atmosphere, extreme cold, dust storms. Not great for picnics.',
  narnia: 'Always winter, never Christmas. Unless Aslan says otherwise.',
  mordor: 'One does not simply check the weather in Mordor.',
  hogwarts: 'Enchanted ceiling in the Great Hall. No app needed.',
  gotham: 'Dark and brooding, with a chance of Batman.',
  wakanda: 'Weather technology centuries ahead of this app.',
  westeros: "Winter is coming. Or it's here already. Or it's summer. We're not sure.",
  'bikini bottom': "It's already underwater, what more do you want to know?",
  'springfield': "Expect yellow skies and a general sense of unease.",
  'sunnydale': "High chance of vampires. And rain.",
  'mount doom': "Volcanic activity. Bring a fire extinguisher.",
  'the shire': "Pleasant weather for hobbits. Slight chance of orcs.",
  'neverland': "Weather is whatever you believe it to be.",
  'asgard': "Prepare for thunder, lightning, and the occasional rainbow bridge.",
  'titan': "Dusty. Very dusty. And possibly crowded.",
  'xandar': "Beautiful skies, but watch out for Ronan.",
  'knowhere': "Expect the unexpected. And maybe some weird creatures.",
};